# Starts a co-located FreeRADIUS for HiveKeeper's PPSK-via-RADIUS runtime ("Caminho B"), in podman, on the
# standard RADIUS ports (1812/1813 UDP). The agent OWNS the user data: it writes a files-module authorize file
# (username -> Cleartext-Password + VLAN reply attrs) that this container reads. HiveKeeper never edits raddb
# by hand — the agent's FilePpskUserStore + FreeRadiusFilesProvisioner regenerate the authorize file on every
# create/rotate/revoke.
#
#   powershell -File scripts/dev-radius.ps1 [-RadiusDir <dir>] [-Secret <shared-secret>]
#   then run the agent with:
#     $env:HIVEKEEPER_PPSK_STORE = "<dir>\ppsk.properties"
#     $env:HIVEKEEPER_RADIUS_DIR = "<dir>"        # where the agent writes the 'authorize' file
#
# Docker users: replace 'podman' with 'docker'. This is a LAB helper — see docs/ppsk-radius-runbook.md for the
# end-to-end validation (pointing a throwaway AP security-object at this server and connecting a real client).
param(
  [string]$RadiusDir = (Join-Path $env:TEMP 'hivekeeper-radius'),
  [string]$Secret = 'testing123'
)
$ErrorActionPreference = 'Stop'

# The directory the AGENT writes the authorize file into and FreeRADIUS reads from. Mounted into the container
# at the files-module path so a regenerated authorize file is picked up on the next request (or a reload).
$null = New-Item -ItemType Directory -Force -Path $RadiusDir
$authorize = Join-Path $RadiusDir 'authorize'
if (-not (Test-Path $authorize)) {
  # Seed an empty authorize file so FreeRADIUS starts cleanly before the agent has provisioned anyone.
  Set-Content -Path $authorize -Value "# managed by hive-agent — generated`n" -Encoding utf8
}

# Point the AP at this server with the SAME shared secret. clients.conf lets the AP's mgt0 subnet talk to us.
$clients = Join-Path $RadiusDir 'clients.conf'
Set-Content -Path $clients -Encoding utf8 -Value @"
client lan {
    ipaddr = 0.0.0.0/0
    secret = $Secret
}
"@

podman rm -f hivekeeper-radius 2>$null | Out-Null
podman run -d --name hivekeeper-radius `
  -p 1812:1812/udp -p 1813:1813/udp `
  -v "${authorize}:/etc/raddb/mods-config/files/authorize:ro" `
  -v "${clients}:/etc/raddb/clients.conf:ro" `
  docker.io/freeradius/freeradius-server:latest | Out-Null

Write-Host "FreeRADIUS starting on :1812/udp (shared-secret '$Secret')" -ForegroundColor Cyan
Write-Host "authorize file: $authorize  (regenerated by the agent)" -ForegroundColor Green
Write-Host 'Run the agent with:' -ForegroundColor Green
Write-Host "  `$env:HIVEKEEPER_PPSK_STORE = '$RadiusDir\ppsk.properties'" -ForegroundColor Green
Write-Host "  `$env:HIVEKEEPER_RADIUS_DIR = '$RadiusDir'" -ForegroundColor Green
Write-Host 'Logs: podman logs -f hivekeeper-radius   (run -X in the container for debug)' -ForegroundColor Yellow
Write-Host 'NOTE: after the agent rewrites authorize, reload with: podman kill -s HUP hivekeeper-radius' -ForegroundColor Yellow
