#!/usr/bin/env bash
# One-time bootstrap for a PRODUCTION HiveKeeper deployment: generates every secret the stack needs and the
# private PKI that agents authenticate with.
#
#   scripts/init-secrets.sh hivekeeper.example.org
#
# Writes:
#   .env.prod        every generated secret (chmod 600). Never commit it; back it up somewhere else.
#   secrets/pki/     ca.p12, gateway.p12, truststore.p12, ca.pem
#
# Idempotent in the only sense that matters: it REFUSES to overwrite. Re-generating the CA would orphan every
# agent already enrolled against the old one, and re-generating HIVEKEEPER_CRYPTO_KEY would make every secret
# already in the database undecryptable — silently, since the ciphertext would still be there. If you mean to
# start over, delete the files yourself and know that you are also throwing away the fleet's enrolment.
#
# keytool runs inside a container, so the server needs no JDK — only a container engine (docker or podman) and
# openssl.
set -euo pipefail

DOMAIN="${1:?usage: init-secrets.sh <public-domain>   e.g. hivekeeper.example.org}"
ENV_FILE="${ENV_FILE:-.env.prod}"
PKI_DIR="${PKI_DIR:-secrets/pki}"
JRE_IMAGE="${JRE_IMAGE:-eclipse-temurin:21-jre}"

ENGINE="${CONTAINER_ENGINE:-}"
if [ -z "$ENGINE" ]; then
  if command -v docker >/dev/null 2>&1; then ENGINE=docker
  elif command -v podman >/dev/null 2>&1; then ENGINE=podman
  else echo "need docker or podman on PATH" >&2; exit 1
  fi
fi

if [ -e "$ENV_FILE" ] || [ -e "$PKI_DIR" ]; then
  echo "REFUSING to overwrite: $ENV_FILE or $PKI_DIR already exists." >&2
  echo "Re-generating the CA orphans every enrolled agent; re-generating the crypto key makes every secret" >&2
  echo "already in the database permanently unreadable. Delete them by hand if that is really what you want." >&2
  exit 1
fi

secret() { openssl rand -base64 32 | tr -d '\n'; }
# Store passwords go into a keystore AND an env file, so keep them free of quoting hazards.
password() { openssl rand -hex 24; }

mkdir -p "$PKI_DIR"
STORE_PASS="$(password)"

echo ">> generating the private PKI for ${DOMAIN} (CA + gateway server certificate)"
# keytool inside a container: no JDK needed on the server. The PKI directory is mounted at /pki.
$ENGINE run --rm -v "$(pwd)/${PKI_DIR}:/pki:z" -w /pki "$JRE_IMAGE" bash -euc "
  P='${STORE_PASS}'

  # The CA. It signs every agent's certificate — the gateway's enrollment endpoint uses this keystore, so its
  # private key IS the fleet's trust. Losing it means re-enrolling every agent.
  keytool -genkeypair -alias ca -keyalg RSA -keysize 4096 -validity 3650 \
    -dname 'CN=HiveKeeper CA,O=HiveKeeper' -ext bc:c \
    -keystore ca.p12 -storetype PKCS12 -storepass \"\$P\" -keypass \"\$P\"
  keytool -exportcert -alias ca -rfc -file ca.pem -keystore ca.p12 -storepass \"\$P\"

  # The truststore is the CA alone: it is what makes an agent's certificate verifiable, on both sides.
  keytool -importcert -noprompt -alias ca -file ca.pem \
    -keystore truststore.p12 -storetype PKCS12 -storepass \"\$P\"

  # The gateway's SERVER certificate, for the agent-facing TLS port. Its SAN must contain the host agents
  # dial, or they will refuse the connection — correctly.
  keytool -genkeypair -alias gateway -keyalg RSA -keysize 2048 -validity 825 \
    -dname 'CN=${DOMAIN},O=HiveKeeper' -ext 'san=dns:${DOMAIN}' \
    -keystore gateway.p12 -storetype PKCS12 -storepass \"\$P\" -keypass \"\$P\"
  keytool -certreq -alias gateway -file gateway.csr -keystore gateway.p12 -storepass \"\$P\"
  keytool -gencert -alias ca -ext 'san=dns:${DOMAIN}' -validity 825 -rfc \
    -infile gateway.csr -outfile gateway.crt -keystore ca.p12 -storepass \"\$P\"
  keytool -importcert -noprompt -alias ca -file ca.pem -keystore gateway.p12 -storepass \"\$P\"
  keytool -importcert -noprompt -alias gateway -file gateway.crt -keystore gateway.p12 -storepass \"\$P\"

  rm -f gateway.csr gateway.crt
"

echo ">> writing ${ENV_FILE}"
umask 077
cat > "$ENV_FILE" <<EOF
# HiveKeeper production secrets — generated by scripts/init-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
#
# BACK THIS FILE UP, somewhere other than this machine, and never commit it.
#   HIVEKEEPER_CRYPTO_KEY  decrypts every secret in the database. Lose it and durable jobs, sealed
#                          credentials and minted PSKs are all unreadable — the data is still there, just gone.
#   secrets/pki/ca.p12     signs every agent certificate. Lose it and the whole fleet must re-enroll.

# --- Where this deployment lives -----------------------------------------------------------------------
# The public hostname. Caddy gets a TLS certificate for it automatically, so it must resolve to this machine
# and 80/443 must be reachable, or the certificate cannot be issued.
HIVEKEEPER_DOMAIN=${DOMAIN}

# Pin the release. Never :latest in production — an unattended restart would silently upgrade you.
HIVEKEEPER_REGISTRY=ghcr.io/ggfto
HIVEKEEPER_TAG=${HIVEKEEPER_TAG:-0.6.0}

# --- Secrets -------------------------------------------------------------------------------------------
# Encrypts job secrets and sealed credentials at rest, in the database.
HIVEKEEPER_CRYPTO_KEY=$(secret)

# Database.
HIVEKEEPER_DB_PASSWORD=$(password)
HIVEKEEPER_DB_ADMIN_PASSWORD=$(password)

# Keycloak: its own database, and the admin account the gateway uses to create users.
KEYCLOAK_DB_PASSWORD=$(password)
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=$(password)

# The private PKI (secrets/pki). One password for all three stores.
HIVEKEEPER_TLS_KEYSTORE_PASSWORD=${STORE_PASS}
HIVEKEEPER_TLS_TRUSTSTORE_PASSWORD=${STORE_PASS}
HIVEKEEPER_CA_KEYSTORE_PASSWORD=${STORE_PASS}

# --- Sign in with GitHub (optional) --------------------------------------------------------------------
# Create a GitHub OAuth App with this exact Authorization callback URL:
#   https://${DOMAIN}/auth/realms/hivekeeper/broker/github/endpoint
# Then fill these in and bring the stack up again. Left empty, sign-in is username + password only.
HIVEKEEPER_GITHUB_CLIENT_ID=
HIVEKEEPER_GITHUB_CLIENT_SECRET=
EOF
chmod 600 "$ENV_FILE"

cat <<EOF

Done.

  ${ENV_FILE}          every secret (chmod 600) — back it up, do not commit it
  ${PKI_DIR}/ca.p12          the CA: signs agent certificates
  ${PKI_DIR}/gateway.p12     the gateway's server certificate for the agent port
  ${PKI_DIR}/truststore.p12  the CA alone
  ${PKI_DIR}/ca.pem          the CA certificate, to hand to each agent (public — not a secret)

Next:
  1. Point ${DOMAIN} at this machine (A/AAAA) and open 80, 443 and 9443.
       80/443  the console and Keycloak, behind Caddy.
       9443    the agents. NOT behind the proxy: they authenticate with a client certificate, which a
               TLS-terminating proxy would swallow.
  2. docker compose --env-file ${ENV_FILE} -f docker-compose.prod.yml up -d
  3. Open https://${DOMAIN} and complete first-run setup with the token from: docker compose logs gateway
EOF
